"""aggiungi anonimizzato_at a users

Revision ID: 2eac6f32b19b
Revises: 215aa000de4b
Create Date: 2026-08-25 18:05:22.827251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eac6f32b19b'
down_revision: Union[str, Sequence[str], None] = '215aa000de4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anonimizzato_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anonimizzato_at')
    # ### end Alembic commands ###
